export const CREATE_TAREA = "CREATE_TAREA";
export const RETRIEVE_TAREAS = "RETRIEVE_TAREAS";
export const UPDATE_TAREA = "UPDATE_TAREA";
export const DELETE_TAREA = "DELETE_TAREA";
export const DELETE_ALL_TAREAS = "DELETE_ALL_TAREAS";